### ISSUE TITLE
Could you add an open-source license

### ISSUE THREAD

**Issue by Zackhardtoname** [Teddy-Mengistie/Leetcode-Bot#1]
Great bot! Any chance you could give the project an open-source license like MIT or GPL-3.0 license?

**Comment by Zackhardtoname** [comment]
Also may I ask where the bot resides now?

**Comment by Teddy-Mengistie** [comment]
Added the licensing, and could you elaborate on your question? Do you mean what discord server the bot is in?

**Comment by Zackhardtoname** [comment]
Yes!

**Comment by Teddy-Mengistie** [comment]
Oh I am currently running it in a server with a group of friends, you can run your own bot and invite it to your own server with https://discord.com/developers/applications.

**Comment by Teddy-Mengistie** [comment]
If you have any additions you want to make to the repo, please make as many PRs as you want. I have been super busy recently that I could not add more features but I will be back at it soon.

**Comment by Zackhardtoname** [comment]
Got it! Thank you!
